# -*- coding: utf-8 -*-
"""Positive_number.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T_ndEhJOZ_TY3RDmQyG-Dv905oTzM_Cx
"""

def print_positive_numbers_comp(numbers):
  """Prints only the positive integers from a list using list comprehension.

  Args:
      numbers: A list of numbers.
  """

  positive_numbers = [num for num in numbers if num > 0]
  print(*positive_numbers)  # Unpack the list elements for printing

list1 = [12, -7, 5, 64, -14]
print_positive_numbers_comp(list1)

list2 = [12, 14, -95, 3]
print_positive_numbers_comp(list2)